manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: AlexNasarreRodriguez
      url-base: https://github.com/AlexNasarreRodriguez
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: ZMKlangbehavior
      remote: AlexNasarreRodriguez
      revision: master
      path: modules/ZMKlangbehavior
    - name: ZMKprommtbehaviors
      remote: AlexNasarreRodriguez
      revision: master
      path: modules/ZMKprommtbehaviors
  self:
    path: config